name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Publish Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.ref_name }}
          generate_release_notes: true
          files: install.sh
